name: Test Materials

on:
  push:
    branches:
      - main

jobs:
  find-files:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.get-materials.outputs.files }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get list of materials
      id: get-materials
      run: |
        files=$(find materials/ -path "*/completed/*.py" -type f -not -path "*/archive/*" | tr '\n' ' ')
        echo "::set-output name=files::$files"

  run-tests:
    needs: find-files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gem5/devcontainer:bootcamp-2024

    strategy:
      matrix:
        file: ${{fromJson(needs.find-files.outputs.files)}}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run test
      run: python materials/test-material.py "${{ matrix.file }}"
